name: CI

on:
  push:
    branches: [main]
    paths-ignore: ['**.md', '**.txt']
  pull_request:
    branches: [main]
    paths-ignore: ['**.md', '**.txt']

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - run: npm ci

      - run: npx playwright install --with-deps

      - run: npm run test

      - run: npm run lint

      - run: npx playwright test --workers=1
